//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment_Item
    {
        public int Adjustment_ItemID { get; set; }
        public Nullable<int> AdjustmentID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> AdjustedQty { get; set; }
        public string Reason { get; set; }
        public string Condition { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Item Item { get; set; }
    }
}
