//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement_Item
    {
        public int Disbursement_ItemID { get; set; }
        public Nullable<int> DisbursementID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual Item Item { get; set; }
    }
}
