//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Item
    {
        public int Purchase_ItemID { get; set; }
        public Nullable<int> QtyOrdered { get; set; }
        public Nullable<System.DateTime> DateSupplied { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> DateExpectedDelivery { get; set; }
        public Nullable<int> QuantityReceived { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
