//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition_Item
    {
        public int Requisition_ItemID { get; set; }
        public int RequisitionID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> RequestedQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> UnfulfilledQty { get; set; }
        public string Status { get; set; }
        public Nullable<int> RetrievedQty { get; set; }
        public Nullable<int> ToRetrieveQty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
